### ISSUE TITLE
UI bug when selecting a date range

### ISSUE THREAD

**Issue by bogusbd** [malzariey/filament-daterangepicker-filter#55] opened 2024-01-03 00:54 UTC
Hello,  I don’t quite understand the logic of the bug.... but try to select two dates that are both in the left block and the right block at the same time..... In this case, 4 numbers will be selected  
 
on the DEMO page of the daterangepicker plugin this behavior is not reproduced

![image](https://github.com/malzariey/filament-daterangepicker-filter/assets/1072015/ca1a5cd2-4157-4d2c-b381-e7b344c561da)

**Comment by malzariey** [comment] 2024-01-29 06:31
This is not a bug, DateRangePicker separates each month in a separate calendar (column). In  your case you have selected between two months while the beginning of the next month is in the previous calendar. Using the one column mode would solve your problem.

**Comment by bogusbd** [comment] 2024-04-16 00:05
Hello, @malzariey 
If I'm not mistaken then this plugin uses this library  http://www.daterangepicker.com/#google_vignette
And there, by default, only 2 values are selected.

![image](https://github.com/malzariey/filament-daterangepicker-filter/assets/1072015/3ec6657b-8443-4509-849b-bdbea9aded5d)


Perhaps there is some option that allows me to enable this behavior? 
I think this is more user-friendly behavior... Because when users see 4 selected values, it confuses them for a few seconds))

many thanks

**Comment by malzariey** [comment] 2024-04-16 00:08
> I think this is more user-friendly behavior... Because when users see 4 selected values, it confuses them for a few seconds))

We are using https://www.daterangepicker.com/

I am not sure what exactly is confusing?

**Comment by malzariey** [comment] 2024-04-16 00:10
We use https://www.daterangepicker.com/ . We might need to edit the library to enable this.

Let me reopen the issue. Once I have time I will look further into the enhancement.

**Comment by malzariey** [comment] 2024-04-16 01:31
Sorry for the delay, 

Issue fixed with v2.5.5.

**Closed by malzariey** 2024-04-16 01:31 UTC
Labels: bug
